TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
Preloading suits...
Preloading Toon heads...
Preloading avatars...
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1777BC38>}
__handleAvatarChooserDone: 100000020, 'Vibrant Cat', ('cls', 'ls', 'm', 'm', (0.96, 0.69, 0.69, 1.0), (1.0, 1.0, 1.0, 1.0), (0.96, 0.69, 0.69, 1.0), (0.96, 0.69, 0.69, 1.0), 18, 1, 12, 1, 6, 9), 5
__handleAvatarChooserDone: 100000034, 'Tom Bumberpop (Mod)', ('css', 'ms', 'm', 'm', (1.0, 1.0, 1.0, 1.0), (0.93, 0.26, 0.28, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), 66, 27, 55, 27, 17, 27), 0
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_8/dna/storage_DL.pdna
Reading DNA file... phase_8/dna/storage_DL_sz.pdna
Reading DNA file... phase_8/dna/donalds_dreamland_sz.pdna
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_8/dna/storage_BR.pdna
Reading DNA file... phase_8/dna/winter_storage_BR.pdna
Reading DNA file... phase_8/dna/storage_BR_sz.pdna
Reading DNA file... phase_8/dna/the_burrrgh_sz.pdna
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_5/dna/storage_town.pdna
Reading DNA file... phase_8/dna/storage_BR_town.pdna
Reading DNA file... phase_8/dna/the_burrrgh_3300.pdna
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_5.5/dna/storage_estate.pdna
Reading DNA file... phase_5.5/dna/winter_storage_estate.pdna
Reading DNA file... phase_5.5/dna/estate_1.pdna
entered wait for zone redirect
entered wait for set zone response - 2
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_4/dna/storage_TT.pdna
Reading DNA file... phase_4/dna/winter_storage_TT.pdna
Reading DNA file... phase_4/dna/winter_storage_TT_sz.pdna
Reading DNA file... phase_4/dna/storage_TT_sz.pdna
Reading DNA file... phase_4/dna/toontown_central_sz.pdna
Exception occurred while processing Func-clearTransparency-3858 of Parallel-3713:
Parallel-3713:
  0.000 Parallel-3713 {
  0.000   *Particle-11 dur 3
  0.000   Sequence-3712 {
  0.000     Wait dur 0.2
  0.200     Parallel-3708 {
  0.200       Sequence-3711 {
  0.200         Sequence-3709 {
  0.200           *Func-setTransparency-3857
  0.200           LerpColorScaleInterval-3778: color_scale to 1 0.5 1 1 dur 0.3
  0.500           *Func-clearTransparency-3858
  0.500         }
  0.500         Sequence-3710 {
  0.500           *Func-setTransparency-3859
  0.500           LerpColorScaleInterval-3779: color_scale to 1 1 1 1 dur 0.3
  0.800           *Func-clearTransparency-3860
  0.800         }
  0.800         *Func-restoreDefaultColorScale-3861
  0.800       }
  0.800     }
  0.800   }
  3.000 }

Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1829, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 94, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 122, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 519, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 495, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.10.0\direct\interval\Interval.py", line 206, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.10.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 5644 of panda/src/pgraph/nodePath.cxx
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 34, in run
    taskMgr.run()
  File "C:\Panda3D-1.10.0\direct\task\Task.py", line 508, in run
    self.step()
  File "C:\Panda3D-1.10.0\direct\task\Task.py", line 465, in step
    self.mgr.poll()
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1829, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 94, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 122, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 519, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 495, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.10.0\direct\interval\Interval.py", line 206, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.10.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 5644 of panda/src/pgraph/nodePath.cxx
