TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
Preloading suits...
Preloading Toon heads...
Preloading avatars...
{420001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x157AF760>, 401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x157AFAF8>, 4600001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x157AF828>, 4500001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x157AF9B8>, 4400001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x157AFAA8>}
__handleAvatarChooserDone: 100000029, 'Tom Bumberpop', ('rss', 'ms', 'm', 'm', (1.0, 1.0, 1.0, 1.0), (0.93, 0.26, 0.28, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), 89, 27, 76, 27, 45, 27), 1
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_4/dna/storage_TT.pdna
Reading DNA file... phase_4/dna/storage_TT_sz.pdna
Reading DNA file... phase_4/dna/toontown_central_sz.pdna
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_4/dna/storage_TT.pdna
Reading DNA file... phase_4/dna/storage_TT_sz.pdna
Reading DNA file... phase_4/dna/toontown_central_sz.pdna
Exception occurred while processing Func-hide-170 of Sequence-229:
Sequence-229:
  0.000 Sequence-229 {
  0.000   Wait dur 0.1
  0.100   Wait dur 6
  6.100   LerpColorScaleInterval-274: color_scale to 1 1 1 0 dur 0.5
  6.600   *Func-hide-170
  6.600 }

Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1829, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 94, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 117, in __doPythonCallbacks
    ival.privPostEvent()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 519, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 495, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.10.0\direct\interval\Interval.py", line 206, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.10.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 2271 of c:\users\john\desktop\panda3d-master\built\include\nodePath.I
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 34, in run
    taskMgr.run()
  File "C:\Panda3D-1.10.0\direct\task\Task.py", line 508, in run
    self.step()
  File "C:\Panda3D-1.10.0\direct\task\Task.py", line 465, in step
    self.mgr.poll()
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1829, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 94, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 117, in __doPythonCallbacks
    ival.privPostEvent()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 519, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 495, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.10.0\direct\interval\Interval.py", line 206, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.10.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 2271 of c:\users\john\desktop\panda3d-master\built\include\nodePath.I
